routes/admin.php
<?php

Route::get('login', 'Auth\Admin\LoginController@showLoginForm')
    ->name('login.form');

Route::post('login', 'Auth\Admin\LoginController@login')
    ->name('login');

Route::get('logout', 'Auth\Admin\LoginController@logout')
    ->name('logout');
    
Route::get('register', 'Auth\Admin\RegisterController@showRegistrationForm')
    ->name('register.form');

Route::post('register', 'Auth\Admin\RegisterController@register')
    ->name('register');


Route::get('test', 'Admin\ProcessingUsersController@GetInfoPost')
    ->name('test');

Route::get('hotface', 'Admin\ProcessCronJobDataController@processIF')
    ->name('hotface');

Route::namespace ('Admin')
    ->middleware('auth:admin')
    ->group(function () {
        Route::get('/', 'HotFaceController@index')
            ->name('index');

        Route::get('tokens/add-many', 'TokenController@showAddMany')
        ->name('tokens.showAddMany');
        Route::post('tokens/add-many', 'TokenController@addMany')
        ->name('tokens.addMany');

        Route::get('hotfaces/add-many', 'HotFaceController@showAddMany')
        ->name('hotfaces.showAddMany');
        Route::post('hotfaces/add-many', 'HotFaceController@addMany')
        ->name('hotfaces.addMany');

        Route::get('hotfaces/rawdata', 'HotFaceController@rawData')
            ->name('hotfaces.raw');

        Route::get('hotfaces/warning/{id}', 'HotFaceController@warning')
            ->name('hotfaces.warning');


        Route::get('hotfaces/rawdata/delete/{id}', 'HotFaceController@hideraw')
            ->name('hotfaces.raw.hide');

        Route::resources([
            'hotfaces'  => 'HotFaceController',
            'tokens'  => 'TokenController'
        ]);

    });

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('test','HomeController@test')->name('test');

Route::prefix('admin')
    ->as('admin.')
    ->group(function () {
        require base_path('routes/admin.php');
    });

resources/views/partials/admin/alert.blade.php
<div class="alert {{ $class or 'alert-info' }} {{ !empty($dismissible) ? 'alert-dismissible' : '' }}" role="alert">
	@if (!empty($dismissible))
		<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Đóng</span></button>
	@endif
	{!! $message or $slot !!}
</div>

resources/views/partials/admin/errors.blade.php
@if (count($errors) > 0)
    @component('partials.admin.alert')
        @slot('class', isset($class) ? $class : 'alert-danger')
        @slot('dismissible', isset($dismissible) ? $dismissible : false)
        <ul>
            @foreach ($errors->all() as $error)
                <li>{!! $error !!}</li>
            @endforeach
        </ul>
    @endcomponent
@endif

resources/views/partials/admin/navbar.blade.php
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-minimize">
            <button id="minimizeSidebar" class="btn btn-warning btn-fill btn-round btn-icon">
                <i class="fa fa-ellipsis-v visible-on-sidebar-regular"></i>
                <i class="fa fa-navicon visible-on-sidebar-mini"></i>
            </button>
        </div>
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/admin">Admin</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="/">
                        <i class="pe-7s-home"></i>
                        <p>Quay lại trang chủ</p>
                    </a>
                </li>
                <li class="dropdown dropdown-with-icons">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-list"></i>
                        <p class="hidden-md hidden-lg">
                            More
                            <b class="caret"></b>
                        </p>
                    </a>
                    <ul class="dropdown-menu dropdown-with-icons">
                        <li>
                            <a href="{{ route('admin.logout') }}" class="text-danger">
                                <i class="pe-7s-close-circle"></i>
                                Log out
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

resources/views/partials/admin/sidebar.blade.php
<div class="sidebar" data-color="black" style="background-image: url( {{ asset('images/admin/full-screen-image-3.jpg') }} ) ">
    <div class="logo">
        <a href="#" class="logo-text">
            Admin
        </a>
    </div>
    <div class="logo logo-mini">
        <a href="#" class="logo-text">
            Admin
        </a>
    </div>
    <div class="sidebar-wrapper">
        <div class="user">
            <div class="photo">
                <img src="{{ asset('images/admin/default-avatar.png') }}" />
            </div>
            <div class="info">
                <a data-toggle="collapse" href="#collapseExample" class="collapsed">
                    {{-- {{ user()->name }} --}}Admin
                </a>
            </div>
        </div>
        <ul class="nav">
            <li class={{ active_route('admin.hotfaces.*') }}>
                <a href="{{ route('admin.hotfaces.index') }}">
                    <i class="fa fa-user-circle" aria-hidden="true"></i>
                    <p>Danh sách Uid</p>
                </a>

            </li>
            <li>
                <a href="{{ route('admin.hotfaces.raw') }}">
                    <i class="fa fa-user-circle" aria-hidden="true"></i>
                    <p>List raw</p>
                </a>
            </li>
            <li class={{ active_route('admin.tokens.*') }}>
                <a href="{{ route('admin.tokens.index') }}">
                    <i class="fa fa-qrcode" aria-hidden="true"></i>
                    <p>Danh sách token</p>
                </a>
            </li>

            {{-- <li class={{ active_route('admin.emails.*') }}>
                <a href="{{ route('admin.emails.index') }}">
                    <i class="pe-7s-mail"></i>
                    <p>Email nhận thông báo</p>
                </a>
            </li> --}}
        </ul>
    </div>
</div>