routes/admin.php
<?php

Route::get('login', 'Auth\Admin\LoginController@showLoginForm')
    ->name('login.form');

Route::post('login', 'Auth\Admin\LoginController@login')
    ->name('login');

Route::get('logout', 'Auth\Admin\LoginController@logout')
    ->name('logout');
    
Route::get('register', 'Auth\Admin\RegisterController@showRegistrationForm')
    ->name('register.form');

Route::post('register', 'Auth\Admin\RegisterController@register')
    ->name('register');


Route::get('test', 'Admin\ProcessingUsersController@GetInfoPost')
    ->name('test');

Route::get('hotface', 'Admin\ProcessCronJobDataController@processIF')
    ->name('hotface');

Route::namespace ('Admin')
    ->middleware('auth:admin')
    ->group(function () {
        Route::get('/', 'HotFaceController@index')
            ->name('index');

        Route::get('tokens/add-many', 'TokenController@showAddMany')
        ->name('tokens.showAddMany');
        Route::post('tokens/add-many', 'TokenController@addMany')
        ->name('tokens.addMany');

        Route::get('hotfaces/add-many', 'HotFaceController@showAddMany')
        ->name('hotfaces.showAddMany');
        Route::post('hotfaces/add-many', 'HotFaceController@addMany')
        ->name('hotfaces.addMany');

        Route::get('hotfaces/rawdata', 'HotFaceController@rawData')
            ->name('hotfaces.raw');

        Route::get('hotfaces/warning/{id}', 'HotFaceController@warning')
            ->name('hotfaces.warning');


        Route::get('hotfaces/rawdata/delete/{id}', 'HotFaceController@hideraw')
            ->name('hotfaces.raw.hide');

        Route::resources([
            'hotfaces'  => 'HotFaceController',
            'tokens'  => 'TokenController'
        ]);

    });

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('test','HomeController@test')->name('test');

Route::prefix('admin')
    ->as('admin.')
    ->group(function () {
        require base_path('routes/admin.php');
    });

app/Models/HotFace.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Jenssegers\Mongodb\Eloquent\SoftDeletes;
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;
use App\Jobs\V3CreateDataForNewUid;

class HotFace extends Eloquent
{
    use SoftDeletes;

    protected $table = 'hot_faces';

    protected $fillable = [
        'name',
        'fb_uid',
        'number_post',
        'sync_like'
    ];

    public static $rules = [
        'fb_uid' => 'required|unique:hot_faces'
    ];

    public static function boot()
    {
        parent::boot();

        static::created(function ($model) {
            V3CreateDataForNewUid::dispatch($model);
        });
        
    }

    public function posts() {
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/Admin/HotFaceController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\HotFace;
use App\Models\HotFaceData;
use App\Models\HotFaceRaw;
use App\Models\Post;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use phpDocumentor\Reflection\DocBlock\Tags\Var_;

class HotFaceController extends Controller
{
    /**
     * Display a listing of the hotface.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $hotfaces = HotFace::withTrashed()->when($request->name, function ($q) use ($request) {
            $q->where('name', 'like', '%' . $request->name . '%')
                ->orWhere('fb_uid', $request->name);
        })->orderBy('created_at','desc')->paginate(20);
        foreach ($hotfaces as $key => $value){
            $listArray[] = $value->_id;
        }

        $new = [];

        if (!$request->name){
            $data = HotFaceData::whereIn('hot_face_id',$listArray)->get();
            $new = array();

            foreach ($data as $value){
                $new[$value->hot_face_id] = $value;
            }
        }


        return view('admin.hotfaces.index', compact('hotfaces','new'));
    }

    /**
     * Show the form for creating a new hotface.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('admin.hotfaces.edit', $this->createOrEdit());
    }

    /**
     * Store a newly created hotface in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\HotFace $hotface
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, HotFace::$rules);

        $this->storeOrUpdate($request);

        flash()->success("Lưu thành công");

        return redirect()->route('admin.hotfaces.index');
    }

    /**
     * Display the specified hotface.
     *
     * @param  \App\HotFace $hotface
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show(HotFace $hotface)
    {

        $data = HotFaceData::where('hot_face_id', $hotface->id)->first();
        $posts = Post::where('hot_face_id', $hotface->id)->orderBy('fb_created', 'desc')->limit(intval($hotface->number_post))->get();
        return view('admin.hotfaces.show', compact('hotface', 'posts','data'));

    }


    public function warning($id){

        $user = HotFace::find($id);
        $user->warning = '1';
        $test = $user->save();

        if($test){
            return response()->json([
                'status'  => 200,
                'message' => 'Success',
            ]);
        }

    }

    /**
     * Show the form for editing the specified hotface.
     *
     * @param  \App\HotFace $hotface
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(HotFace $hotface)
    {

        return view('admin.hotfaces.edit', $this->createOrEdit($hotface));
    }

    /**
     * Update the specified hotface in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\HotFace $hotface
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, HotFace $hotface)
    {

        $rules = [
            'fb_uid' => 'required',
        ];
        $this->validate($request, $rules);
        $this->storeOrUpdate($request, $hotface);

        flash()->success('Lưu thành công');

        return back();
    }

    /**
     * Store or update a hotface.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\HotFace|null $blog
     * @return \App\Models\HotFace
     */
    protected function storeOrUpdate(Request $request, HotFace $hotface = null)
    {
        $hotface = $hotface ?: new HotFace;
        $data    = $request->all();
        $hotface->fill($data);

        $hotface->save();

        return $hotface;
    }

    /**
     * Remove the specified hotface from storage.
     *
     * @param  \App\Models\HotFace $hotface
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(HotFace $hotface)
    {

        $hotface->delete();

        if (request()->ajax()) {
            return response()->json([
                'message'  => trans('hotface.deleted'),
                'redirect' => route('admin.hotfaces.index'),
            ]);
        }

        flash()->success('Xóa thành công');

        return redirect()->route('admin.hotfaces.index');
    }

    /**
     * Get create or add view params.
     *
     * @param  \App\Models\HotFace $hotface
     * @return array
     */
    protected function createOrEdit(HotFace $hotface = null)
    {
        $hotface = $hotface ?: new HotFace;
        $url     = $hotface->id
        ? route('admin.hotfaces.update', [$hotface->id])
        : route('admin.hotfaces.store');
        return compact('hotface', 'url');
    }

    public function showAddMany()
    {
        return view('admin.hotfaces.add-many');
    }

    public function addMany(Request $request)
    {
        $number_post = $request->number_post;
        $sync_like   = $request->sync_like;
        $raw         = $request->content;
        $arr         = explode(",", $raw);
        $newArr      = [];
        foreach ($arr as $key => $item) {
            $newArr[] = trim($item);
        }
        $count = 0;
        foreach ($newArr as $key => $content) {
            if (strlen($content) > 10) {
                $hotface = HotFace::where('fb_uid', $content)->first();

                if (!$hotface) {
                    $hotface              = new HotFace();
                    $hotface->number_post = $number_post;
                    $hotface->sync_like   = $sync_like;
                    $hotface->fb_uid      = $content;
                    $hotface->save();
                    $count++;
                }
            }
        }
        flash()->success("Thêm mới thành công " . $count . " uid!");

        return redirect()->route('admin.hotfaces.index');
    }

    public function rawData(){
        $data    =  HotFaceRaw::where('hide','!=',1)->paginate(20);
        return view('admin.hotfaces.raw',compact('data'));
    }

    public function hideraw($id){

        $data = HotFaceRaw::find($id);
        $data->hide = 1;
        $data->save();



       return Redirect::back();

    }

}

resources/views/admin/hotfaces/add-many.blade.php
@extends('layouts.admin')


@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card" >
                    <div class="header">
                        <legend>Thêm mới Nhiều Uid</legend>
                    </div>
                    <div class="content">
                        @include('partials.admin.errors')
                		@include('flash::message')
                    </div>
                    <div class="content">
                    	{!! Form::open() !!}
		                <div class="row">
                        	<div class="col-md-12">
                                <div class="form-group">
                                	{!! Form::label('content', 'Fb Uid',[
                                			'for' => 'content'
                                		]) !!}
		                            {!! Form::textarea('content',null , [
                                            'class' => 'form-control',
                                            'rows' => '8',
                                            'placeholder' => 'Các uid cách nhau bởi dấy phẩy',
                                        ]) 
                                    !!}
                                </div>
                        	</div>
                        	<div class="col-md-6">
                                <div class="form-group">
                                    {!! Form::label('number_post', 'Số lượng bài viết muốn lấy',[
                                            'for' => 'number_post'
                                        ]) !!}
                                    {!! Form::number('number_post', 50, [
                                        'placeholder' => 'Số lượng bài viết muốn lấy',
                                        'class' => 'form-control'
                                    ]) !!}
                                </div>   
                            </div>
                    		<div class="col-md-6">
                                <div class="form-group">
                                    {!! Form::label('sync_like', 'Quét danh sách like',[
                                            'for' => 'sync_like'
                                        ]) !!}
                                    {!! Form::select('sync_like', ['1' => 'Có', '0' => 'Không'], request('sync_like',1), [
                                        'class' => 'form-control',
                                        'data-toggle' => 'type',
                                    ]) !!}
                                </div>
                            </div>
				            <div class="col-md-6">
				            	<div class="row text-center">
			                        <div class="form-group">
			                            {!! Form::submit('Lưu', [
			                                'class' => 'btn btn-primary btn-fill',
			                            ]) !!}
			                        </div>
		                    	</div>
                        	</div>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/hotfaces/edit.blade.php
@extends('layouts.admin')


@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card" >
                    <div class="header">
                        <legend>{{ $hotface->id ? 'Sửa hotface' : 'Thêm mới' }}</legend>
                    </div>
                    <div class="content">
                        @include('partials.admin.errors')
                        @include('flash::message')
                    </div>
                    <div class="content">
                    	{!! Form::model($hotface, [
		                    'url' => $url,
		                    'role' => 'form',
		                    'method' => $hotface->id ? 'PUT' : 'POST',
		                    'files' => true,
		                ]) !!}
    		                <div class="row">
                            	<div class="col-md-6">
        		                    	<div class="form-group">
                                        	{!! Form::label('fb_uid', 'Uid',[
                                        			'for' => 'fb_uid',
                                        		]) !!}
        		                            {!! Form::text('fb_uid', old('fb_uid'), [
        		                                'placeholder' => 'Uid',
        		                                'class' => 'form-control'
        		                            ]) !!}
                                        </div>
                                    <div class="form-group">
                                    	{!! Form::label('number_post', 'Số lượng bài viết muốn lấy',[
                                    			'for' => 'number_post'
                                    		]) !!}
    		                            {!! Form::number('number_post', $hotface->number_post ?: 50, [
    		                                'placeholder' => 'Số lượng bài viết muốn lấy',
    		                                'class' => 'form-control'
    		                            ]) !!}
                                    </div>
                            	</div>
                        		<div class="col-md-6">
                        			<div class="form-group">
                            			{!! Form::label('sync_like', 'Quét danh sách like',[
                                    			'for' => 'sync_like'
                                    		]) !!}
    					                {!! Form::select('sync_like', ['1' => 'Có', '0' => 'Không'], request('sync_like',1), [
    					                    'class' => 'form-control',
    					                    'data-toggle' => 'type',
    					                ]) !!}
    					            </div>
    				            </div>
    				            <div class="col-md-6">
    				            	<div class="row text-center">
    			                        <div class="form-group">
    			                            {!! Form::submit('Lưu', [
    			                                'class' => 'btn btn-primary btn-fill',
    			                            ]) !!}
    			                        </div>
    		                    	</div>
                            	</div>
                            </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/hotfaces/index.blade.php
@extends('layouts.admin')

@section('content')

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                        <h4 class="title">Danh sách Uid</h4>
                    </div>
                    <div class="content">
                        @include('partials.admin.errors')
                        @include('flash::message')
                    </div>
                    <div class="fixed-table-toolbar">
                        <div class="columns columns-right pull-right">
                            <a href="{{ route('admin.hotfaces.create') }}" class="btn btn-default" type="button" name="refresh" title="Refresh"><i class="glyphicon fa fa-plus"></i>Thêm mới</a>
                            <a href="{{ route('admin.hotfaces.addMany') }}" class="btn btn-default" type="button" name="refresh" title="Refresh"><i class="glyphicon fa fa-plus"></i>Thêm nhiều</a>
                        </div>
                        <div class="bars pull-right">
                            <div class="toolbar ">
                                <form class="form-inline" method="GET" action="{{ route('admin.hotfaces.index') }}">
                                    <input class="form-control" type="text" name="name" placeholder="Tên, Uid ..." value="{{ request('name') }}">
                                    <button type="submit" class="btn btn-info">Tìm</button>
                                </form>
                            </div>
                        </div>
                        {{-- <div class="columns columns-right pull-right">
                            <a href="{{ route('admin.hotfaces.create') }}" class="btn btn-default" type="button" name="refresh" title="Refresh"><i class="glyphicon fa fa-plus"></i>Thêm mới</a>
                        </div> --}}
                    </div>
                    <table class="table">
                        <thead>
                            <th>#</th>
                            <th>Status</th>
                            <th>Uid</th>
                            <th>Tên</th>
                            <th>Ngày thêm</th>
                            <th>Hành động</th>
                        </thead>
                        <tbody>
                            @php
                                $i = (request('page', 1) - 1) * 20;
                            @endphp
                            @foreach ($hotfaces as $hotface)
                                <tr>
                                    <td>{{ ++$i }}
                                        @if( isset($new[$hotface->_id]) && $new[$hotface->_id]->like_per_post < 300 && $new[$hotface->_id]->comment_per_post < 20)
                                            <a class="text-warning" style="font-size: 15px">
                                                <i class="glyphicon glyphicon-warning-sign"></i>
                                            </a>
                                        @endif
                                    </td>
                                    <td>
                                        @if ($hotface->trashed())
                                            <span class="label label-danger">Not found</span>
                                        @else
                                            <span class="label label-success">Acvite</span>
                                        @endif
                                    </td>
                                    <td>
                                        <a href="{{ route('admin.hotfaces.show',$hotface->id) }}">{{ $hotface->fb_uid }}</a>
                                    </td>
                                    <td>{{ $hotface->name }}</td>
                                    <td>{{ $hotface->created_at->format('H:i d/m/y') }}</td>
                                    <td class="td-actions" style="">
                                        <a rel="tooltip" title="" class="btn btn-simple btn-warning btn-icon table-action edit" href="{{ route('admin.hotfaces.edit', $hotface->_id) }}" data-original-title="Chỉnh sửa"><i class="fa fa-edit"></i></a>

                                        <a rel="tooltip" title="" class="btn btn-simple btn-danger btn-icon table-action remove" href="{{ route('admin.hotfaces.destroy', $hotface->id) }}" data-original-title="Xóa" data-swal="{{ json_encode(swal([
                                                    'title' => 'Are you sure',
                                                    'type' => 'question',
                                                    'showCancelButton' => true,
                                                ])) }}"
                                                data-swal-method="DELETE"><i class="fa fa-remove"></i></a>



                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <div class="fixed-table-pagination">
                        <div class="pull-right pagination">
                            {{ $hotfaces->appends(request()->query())->links() }}
                        </div>
                    </div>
                </div>
                <!--  end card  -->
            </div>
            <!-- end col-md-12 -->
        </div>
        <!-- end row -->
    </div>
</div>

@endsection

resources/views/admin/hotfaces/raw.blade.php
@extends('layouts.admin')

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="header"> <h4>List data raw</h4></div>
                        <div class="content">
<!--                            --><?php //var_dump($data); ?>
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Follower</th>
                                        <th>FB Link</th>
                                        <th>Gender</th>
                                        <th>hide</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php $i = (request('page', 1) - 1) * 20; ?>
                                    @foreach($data as $key => $value)
                                        <tr>
                                            <td>{{ ++$i }}</td>
                                            <td>{{ $value->count_followers }}</td>
                                            <td><a target="_blank" href="{{'https://www.facebook.com/'. $value->fb_uid}}">Link</a></td>
                                            <td>{{ $value->gender  }}</td>
                                            <td>
                                                <a rel="tooltip" title="" class="btn btn-simple btn-danger btn-icon table-action remove"
                                                   href="{{route('admin.hotfaces.raw.hide', ['id' => $value->_id])}}"
                                                    aria-describedby="tooltip791706">
                                                    <i class="fa fa-remove"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>

                            {{--{{ $data->links() }}--}}
                        </div>
                    </div>
                    <div class="fixed-table-pagination">
                        <div class="pull-right pagination">
                            {{ $data->appends(request()->query())->links() }}
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
@endsection