routes/admin.php
<?php

Route::get('login', 'Auth\Admin\LoginController@showLoginForm')
    ->name('login.form');

Route::post('login', 'Auth\Admin\LoginController@login')
    ->name('login');

Route::get('logout', 'Auth\Admin\LoginController@logout')
    ->name('logout');
    
Route::get('register', 'Auth\Admin\RegisterController@showRegistrationForm')
    ->name('register.form');

Route::post('register', 'Auth\Admin\RegisterController@register')
    ->name('register');


Route::get('test', 'Admin\ProcessingUsersController@GetInfoPost')
    ->name('test');

Route::get('hotface', 'Admin\ProcessCronJobDataController@processIF')
    ->name('hotface');

Route::namespace ('Admin')
    ->middleware('auth:admin')
    ->group(function () {
        Route::get('/', 'HotFaceController@index')
            ->name('index');

        Route::get('tokens/add-many', 'TokenController@showAddMany')
        ->name('tokens.showAddMany');
        Route::post('tokens/add-many', 'TokenController@addMany')
        ->name('tokens.addMany');

        Route::get('hotfaces/add-many', 'HotFaceController@showAddMany')
        ->name('hotfaces.showAddMany');
        Route::post('hotfaces/add-many', 'HotFaceController@addMany')
        ->name('hotfaces.addMany');

        Route::get('hotfaces/rawdata', 'HotFaceController@rawData')
            ->name('hotfaces.raw');

        Route::get('hotfaces/warning/{id}', 'HotFaceController@warning')
            ->name('hotfaces.warning');


        Route::get('hotfaces/rawdata/delete/{id}', 'HotFaceController@hideraw')
            ->name('hotfaces.raw.hide');

        Route::resources([
            'hotfaces'  => 'HotFaceController',
            'tokens'  => 'TokenController'
        ]);

    });

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('test','HomeController@test')->name('test');

Route::prefix('admin')
    ->as('admin.')
    ->group(function () {
        require base_path('routes/admin.php');
    });

app/Models/Token.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Jenssegers\Mongodb\Eloquent\SoftDeletes;
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class Token extends Eloquent
{
    use SoftDeletes;

    protected $table = 'tokens';

    protected $fillable = [
    	'content','status'
    ];

    /**
     * Validation rules.
     *
     * @var array
     */
    public static $rules = [
        'content' => 'required|unique:tokens'
    ];

}

app/Http/Controllers/Admin/TokenController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Token;
use Illuminate\Http\Request;

class TokenController extends Controller
{
    /**
     * Display a listing of the token.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $tokens = Token::when($request->content, function ($q) use ($request) {
            return $q->where('content', 'like', '%' . $request->content . '%');
        })->orderBy('created_at','desc')->paginate(20);
        return view('admin.tokens.index', compact('tokens'));
    }

    /**
     * Show the form for creating a new token.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('admin.tokens.edit', $this->createOrEdit());
    }

    /**
     * Store a newly created token in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Token $token
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, Token::$rules);

        $this->storeOrUpdate($request);

        flash()->success("Lưu thành công");

        return redirect()->route('admin.tokens.index');
    }

    /**
     * Display the specified token.
     *
     * @param  \App\Token $token
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show(Token $token)
    {
        // $posts = Post::where('hot_face_id', $token->id)->orderBy('fb_created', 'desc')->limit(intval($token->number_post))->get();
        // return view('admin.tokens.show',compact('token','posts'));
    }

    /**
     * Show the form for editing the specified token.
     *
     * @param  \App\Token $token
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Token $token)
    {

        return view('admin.tokens.edit', $this->createOrEdit($token));
    }

    /**
     * Update the specified token in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Token $token
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Token $token)
    {

        $rules = [
            'content' => 'required',
        ];
        $this->validate($request, $rules);
        $this->storeOrUpdate($request, $token);

        flash()->success('Lưu thành công');

        return back();
    }

    /**
     * Store or update a token.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\Token|null $blog
     * @return \App\Models\Token
     */
    protected function storeOrUpdate(Request $request, Token $token = null)
    {
        $token = $token ?: new Token;
        $data  = $request->all();
        $token->fill($data);

        $token->save();

        return $token;
    }

    /**
     * Remove the specified token from storage.
     *
     * @param  \App\Models\Token $token
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Token $token)
    {

        $token->delete();

        if (request()->ajax()) {
            return response()->json([
                'message'  => trans('token.deleted'),
                'redirect' => route('admin.tokens.index'),
            ]);
        }

        flash()->success('Xóa thành công');

        return redirect()->route('admin.tokens.index');
    }

    /**
     * Get create or add view params.
     *
     * @param  \App\Models\Token $token
     * @return array
     */
    protected function createOrEdit(Token $token = null)
    {
        $token = $token ?: new Token;
        $url   = $token->id
        ? route('admin.tokens.update', [$token->id])
        : route('admin.tokens.store');
        return compact('token', 'url');
    }

    public function showAddMany()
    {
        return view('admin.tokens.add-many');
    }

    public function addMany(Request $request)
    {
        $status = $request->status;
        $raw    = $request->content;
        $arr    = explode(",", $raw);
        $newArr = [];
        foreach ($arr as $key => $item) {
            $newArr[] = trim($item);
        }
        $count = 0;
        foreach ($newArr as $key => $content) {
            if (strlen($content) > 10) {
                $token = Token::where('content', $content)->first();

                if (!$token) {
                    $token          = new Token();
                    $token->status  = $status;
                    $token->content = $content;
                    $token->save();
                    $count++;
                }
            }
        }
        flash()->success("Thêm mới thành công " . $count . " token!");

        return redirect()->route('admin.tokens.index');
    }
}

resources/views/admin/tokens/add-many.blade.php
@extends('layouts.admin')


@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card" >
                    <div class="header">
                        <legend>Thêm mới Nhiều Token</legend>
                    </div>
                    <div class="content">
                        @include('partials.admin.errors')
                		@include('flash::message')
                    </div>
                    <div class="content">
                    	{!! Form::open() !!}
		                <div class="row">
                        	<div class="col-md-12">
                                <div class="form-group">
                                	{!! Form::label('content', 'Content',[
                                			'for' => 'content'
                                		]) !!}
		                            {!! Form::textarea('content',null , [
                                            'class' => 'form-control',
                                            'rows' => '8',
                                            'placeholder' => 'Các token cách nhau bởi dấy phẩy',
                                        ]) 
                                    !!}
                                </div>
                        	</div>
                        	
                    		<div class="col-md-6">
                    			<div class="form-group">
                        			{!! Form::label('status', 'Trạng thái',[
                                			'for' => 'status'
                                		]) !!}
					                {!! Form::select('status', ['1' => 'Kích hoạt', '0' => 'Không kích hoạt'], request('status'), [
					                    'class' => 'form-control',
					                ]) !!}
					            </div>
				            </div>
				            <div class="col-md-6">
				            	<div class="row text-center">
			                        <div class="form-group">
			                            {!! Form::submit('Lưu', [
			                                'class' => 'btn btn-primary btn-fill',
			                            ]) !!}
			                        </div>
		                    	</div>
                        	</div>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/tokens/edit.blade.php
@extends('layouts.admin')


@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card" >
                    <div class="header">
                        <legend>{{ $token->id ? 'Sửa Token' : 'Thêm mới Token' }}</legend>
                    </div>
                    <div class="content">
                        @include('partials.admin.errors')
                		@include('flash::message')
                    </div>
                    <div class="content">
                    	{!! Form::model($token, [
		                    'url' => $url,
		                    'role' => 'form',
		                    'method' => $token->id ? 'PUT' : 'POST',
		                    'files' => true,
		                ]) !!}
		                <div class="row">
                        	<div class="col-md-6">
                                <div class="form-group">
                                	{!! Form::label('content', 'Content',[
                                			'for' => 'content'
                                		]) !!}
		                            {!! Form::textarea('content',$token->content , [
                                            'class' => 'form-control',
                                            'rows' => '4',
                                        ]) 
                                    !!}
                                </div>
                        	</div>
                        	
                    		<div class="col-md-6">
                    			<div class="form-group">
                        			{!! Form::label('status', 'Trạng thái',[
                                			'for' => 'status'
                                		]) !!}
					                {!! Form::select('status', ['1' => 'Kích hoạt', '0' => 'Không kích hoạt'], request('status'), [
					                    'class' => 'form-control',
					                ]) !!}
					            </div>
				            </div>
				            <div class="col-md-6">
				            	<div class="row text-center">
			                        <div class="form-group">
			                            {!! Form::submit('Lưu', [
			                                'class' => 'btn btn-primary btn-fill',
			                            ]) !!}
			                        </div>
		                    	</div>
                        	</div>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/tokens/index.blade.php
@extends('layouts.admin')

@section('content')

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                        <h4 class="title">Danh sách Token</h4>
                    </div>
                    <div class="content">
                        @include('partials.admin.errors')
                        @include('flash::message')
                    </div>
                    <div class="fixed-table-toolbar">
                        <div class="columns columns-right pull-right">
                            <a href="{{ route('admin.tokens.create') }}" class="btn btn-default" type="button" name="refresh" title="Refresh"><i class="glyphicon fa fa-plus"></i>Thêm mới</a>
                            <a href="{{ route('admin.tokens.showAddMany') }}" class="btn btn-default" type="button" name="refresh" title="Refresh"><i class="glyphicon fa fa-plus"></i>Thêm nhiều </a>
                        </div>
                    </div>
                    <div class="bars pull-right">
                            <div class="toolbar ">
                                <form class="form-inline" method="GET" action="{{ route('admin.tokens.index') }}">
                                    <input class="form-control" type="text" name="content" placeholder="Token content ..." value="{{ request('content') }}">
                                    <button type="submit" class="btn btn-info">Tìm</button>
                                </form>
                            </div>
                        </div>
                    <table class="table">
                        <thead>
                            <th>#</th>
                            <th>Trạng thái</th>
                            <th>Content</th>
                            <th>Hành động</th>
                        </thead>
                        <tbody>
                            @php
                                $i = (request('page', 1) - 1) * 20;
                            @endphp
                            @foreach ($tokens as $token)
                                <tr>
                                    <td>{{ ++$i }}</td>
                                    <td>
                                        @if ($token->status == 1)
                                            <span class="label label-success">Acvite</span>
                                        @else
                                            <span class="label label-danger">InAcvite</span>
                                        @endif
                                    </td>
                                    <td>{{ str_limit($token->content,50) }}</td>
                                    <td class="td-actions" style="">
                                        <a rel="tooltip" title="" class="btn btn-simple btn-warning btn-icon table-action edit" href="{{ route('admin.tokens.edit', $token->id) }}" data-original-title="Chỉnh sửa"><i class="fa fa-edit"></i></a>

                                        <a rel="tooltip" title="" class="btn btn-simple btn-danger btn-icon table-action remove" href="{{ route('admin.tokens.destroy', $token->id) }}" data-original-title="Xóa" data-swal="{{ json_encode(swal([
                                                    'title' => 'Are you sure',
                                                    'type' => 'question',
                                                    'showCancelButton' => true,
                                                ])) }}"
                                                data-swal-method="DELETE"><i class="fa fa-remove"></i></a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <div class="fixed-table-pagination">
                        <div class="pull-right pagination">
                            {{ $tokens->appends(request()->query())->links() }}
                        </div>
                    </div>
                </div>
                <!--  end card  -->
            </div>
            <!-- end col-md-12 -->
        </div>
        <!-- end row -->
    </div>
</div>

@endsection