routes/admin.php
<?php

Route::get('login', 'Auth\Admin\LoginController@showLoginForm')
    ->name('login.form');

Route::post('login', 'Auth\Admin\LoginController@login')
    ->name('login');

Route::get('logout', 'Auth\Admin\LoginController@logout')
    ->name('logout');
    
Route::get('register', 'Auth\Admin\RegisterController@showRegistrationForm')
    ->name('register.form');

Route::post('register', 'Auth\Admin\RegisterController@register')
    ->name('register');


Route::get('test', 'Admin\ProcessingUsersController@GetInfoPost')
    ->name('test');

Route::get('hotface', 'Admin\ProcessCronJobDataController@processIF')
    ->name('hotface');

Route::namespace ('Admin')
    ->middleware('auth:admin')
    ->group(function () {
        Route::get('/', 'HotFaceController@index')
            ->name('index');

        Route::get('tokens/add-many', 'TokenController@showAddMany')
        ->name('tokens.showAddMany');
        Route::post('tokens/add-many', 'TokenController@addMany')
        ->name('tokens.addMany');

        Route::get('hotfaces/add-many', 'HotFaceController@showAddMany')
        ->name('hotfaces.showAddMany');
        Route::post('hotfaces/add-many', 'HotFaceController@addMany')
        ->name('hotfaces.addMany');

        Route::get('hotfaces/rawdata', 'HotFaceController@rawData')
            ->name('hotfaces.raw');

        Route::get('hotfaces/warning/{id}', 'HotFaceController@warning')
            ->name('hotfaces.warning');


        Route::get('hotfaces/rawdata/delete/{id}', 'HotFaceController@hideraw')
            ->name('hotfaces.raw.hide');

        Route::resources([
            'hotfaces'  => 'HotFaceController',
            'tokens'  => 'TokenController'
        ]);

    });

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('test','HomeController@test')->name('test');

Route::prefix('admin')
    ->as('admin.')
    ->group(function () {
        require base_path('routes/admin.php');
    });

resources/views/layouts/admin-login.blade.php
<!doctype html>
<html lang="@yield('htmlLang', app()->getLocale())" class="@yield('htmlClass')">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>Admin</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <meta name="csrf-token" content="{{ csrf_token() }}">
    {!! Html::style(mix('css/vendor.css')) !!}
    {!! Html::style(mix('css/admin.css')) !!}
</head>

<body>
<nav class="navbar navbar-transparent navbar-absolute">
    <div class="container">    
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="">Marketing</a>
        </div>
        <div class="collapse navbar-collapse">       
            
            <ul class="nav navbar-nav navbar-right">
                <li>
                    @if (Request::route()->getName() == "admin.register.form")
                        <a href="{{ route('admin.login.form') }}">
                            Login
                        </a>
                    @else
                        <a href="{{ route('admin.register.form') }}">
                            Register
                        </a>
                    @endif
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="wrapper wrapper-full-page">
    <div class="full-page login-page"  data-color="black"   style="background-image: url( {{ asset('images/admin/full-screen-image-3.jpg') }} ) ">   
        
        {{-- <div class="content">
            <div class="container">
                <div class="row">                   
                    <div class="col-md-4 col-sm-6 col-md-offset-4 col-sm-offset-3">
                        <form method="#" action="#">
                            
                            <div class="card">
                                <div class="header text-center">Login</div>
                                <div class="content">
                                    <div class="form-group">
                                        <label>Email address</label>
                                        <input type="email" placeholder="Enter email" class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label>Password</label>
                                        <input type="password" placeholder="Password" class="form-control">
                                    </div>                                    
                                    <div class="form-group">
                                        <label class="checkbox">
                                            <input type="checkbox" data-toggle="checkbox" value="">
                                            Subscribe to newsletter
                                        </label>    
                                    </div>
                                </div>
                                <div class="footer text-center">
                                    <button type="submit" class="btn btn-fill btn-warning btn-wd">Login</button>
                                </div>
                            </div>
                                
                        </form>
                                
                    </div>                    
                </div>
            </div>
        </div> --}}
        @yield('body')
        <footer class="footer footer-transparent">
            <div class="container">
                <p class="copyright pull-right">Chiennd
                </p>
            </div>
        </footer>

    </div>                             
       
</div>
</body>
    {!! Html::script(mix('js/manifest.js')) !!}
    {!! Html::script(mix('js/vendor.js')) !!}
    {!! Html::script('https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=l9i76nao5iygw33yqw0wbfr8g9qljofw54a4novb8dto24cj') !!}
    {!! Html::script(mix('js/admin.js')) !!}
</html>

resources/views/layouts/admin.blade.php
<!doctype html>
<html lang="@yield('htmlLang', app()->getLocale())" class="@yield('htmlClass')">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>Admin</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    {!! Html::style(mix('css/vendor.css')) !!}
    {!! Html::style(mix('css/admin.css')) !!}

    
</head>

<body>
    <div class="wrapper">
        @include('partials.admin.sidebar')
        <div class="main-panel">
            @include('partials.admin.navbar')
            @yield('content')
        </div>
    </div>
</body>
    {!! Html::script(mix('js/manifest.js')) !!}
    {!! Html::script(mix('js/vendor.js')) !!}
    {!! Html::script('https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=l9i76nao5iygw33yqw0wbfr8g9qljofw54a4novb8dto24cj') !!}
    {!! Html::script(mix('js/admin.js')) !!}
</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="icon" href="">

    <title>Blockchain</title>
    
    {!! Html::style(mix('css/app.css')) !!}
    
</head>

<body>

    <header>
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Blockchain</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ route('admin.index') }}"><span class="glyphicon glyphicon-user"></span> Admin</a></li>
                    <li><a href="{{ route('admin.logout') }}"><span class="glyphicon glyphicon-log-in"></span> Đăng xuất</a></li>
                </ul>
              </div>
            </div>
        </nav>
    </header>

<main role="main" id="app">
    @yield('content')
</main>

{{-- <footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
  </p>
  <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
  <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting started guide</a>.</p>
</div>
</footer> --}}


{!! Html::script(mix('js/manifest.js')) !!}
{!! Html::script(mix('js/vendor.js')) !!}
{!! Html::script(mix('js/app.js')) !!}
</body>
</html>